version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=messaging
      - DB_USERNAME=root
      - DB_PASSWORD=
      - APP_ENV=local
      - APP_DEBUG=true

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=messaging
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
